# Generated by Django 3.2.5 on 2021-07-11 17:26

from django.db import migrations, models
import django.db.models.deletion
import djmoney.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('self_cost_currency', djmoney.models.fields.CurrencyField(choices=[('EUR', 'EUR €'), ('RUB', 'RUB ₽'), ('USD', 'USD $')], default='RUB', editable=False, max_length=3)),
                ('self_cost', djmoney.models.fields.MoneyField(decimal_places=2, default_currency='RUB', max_digits=14)),
                ('cost_currency', djmoney.models.fields.CurrencyField(choices=[('EUR', 'EUR €'), ('RUB', 'RUB ₽'), ('USD', 'USD $')], default='RUB', editable=False, max_length=3)),
                ('cost', djmoney.models.fields.MoneyField(decimal_places=2, default_currency='RUB', max_digits=14)),
                ('quantity', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('quantity', models.PositiveIntegerField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('canceled', 'Canceled'), ('refund', 'Refund')], default='pending', max_length=10)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='products.product')),
            ],
        ),
    ]
